apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-from-scratch
  namespace: argocd
spec:
  destination:
    namespace: myapp
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: 02-helm-chart-deployment-on-argo/nginx
    repoURL: 'https://github.com/devilchac/my-argo-proj1.git'
    targetRevision: main
  syncPolicy: {}
  