######### Webapp Service ##############
# apiVersion: v1
# kind: Service
# metadata:
#   name: webapp-service
# spec:
#   selector:
#     app: webapp
#   ports:
#     - name: http
#       port: 80
#       nodePort: 30020
#   type: NodePort