{{- $chartname := .Chart.Name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "basechart.resourcename" . }}-configmap2
data:
{{- range $key,$value := .Values.myappsconfig.config1 }}
{{- $key | nindent 2 }}: {{ $value }}-{{ $chartname }}
{{- end }}