apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "basechart.resourcename" . }}-deployment
  annotations:
    app.kubernetes.io/releaseName: {{ default .Release.Name .Values.releaseName }}
    app.kubernetes.io/releaseRevision: {{ quote .Release.Revision }}
    app.kubernetes.io/releaseService: {{ .Release.Service }}
    app.kubernetes.io/releaseIsInstall: {{ quote .Release.IsInstall }}
    app.kubernetes.io/releaseIsUpgrade: {{ quote .Release.IsUpgrade }}
    app.kubernetes.io/deployedNamespace: {{ .Release.Namespace | lower }}
spec:
{{- if and .Values.myapp.retail.enableFeature ( eq .Values.myapp.env "prod" ) }}
  replicas: 5
{{- else if eq .Values.myapp.env "stag" }}
  replicas: 3
{{- else }}
  replicas: 1
{{- end }}
  selector:
    matchLabels:
      {{- include "basechart.commonlabels" . | indent 2 }}
  template:
    metadata:
      labels:
        {{- include "basechart.commonlabels" . | indent 4 }}
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      containers:
        - name: nginx-container
          image: ghcr.io/stacksimplify/kubenginx:4.0.0
          ports:
            - containerPort: 80
          resources:
          {{- toYaml .Values.resources | nindent 12 }}