apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "basechart.resourcename" . }}-sa
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    helm.sh/chart: nginx-1.0.1
    app.k8s.io/name: webapp
    app.k8s.io/instance: nginx
    app.k8s.io/version: "1.16.0"
    app.k8s.io/instance: {{ .Release.Service }}
