apiVersion: v1
kind: Service
metadata:
  name: {{ include "basechart.resourcename" . }}-service
  labels:
    {{- include "basechart.commonlabels" . | indent 2 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "basechart.commonlabels" . | indent 2 }}