releaseName: cloudneq-webapp-api

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 128Mi
    cpu: 100m

service:
  type: NodePort
  port: 80
  nodePort: 30080

myapp:
  env: stag
  retail:
    enableFeature: true

podAnnotations:
  appName: cloudneq-webapp-api
  appTech: HTML
  appType: frontend
  appDb: mySQL

podConfigMap:
  appName: cloudneq-webapp-api
  appTech: HTML
  appType: frontend
  appDb: mySQL

namespaces1:
  - name: webapp1
  - name: webapp2
  - name: webapp3

environments:
  ns: 
    - dev
    - qa
    - stag
    - prod

# Range with Dictionary
myappsconfig:
  config1: 
    appName: myapp1
    appType: webserver
    appTech: HTML
    appDb: mysql
